# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z045ffg900-2
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc706:part0:1.0 [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
add_files -quiet /scratch/skarandikar/test_ps_sfp/project_1.runs/gig_ethernet_pcs_pma_0_synth_1/gig_ethernet_pcs_pma_0.dcp
set_property used_in_implementation false [get_files /scratch/skarandikar/test_ps_sfp/project_1.runs/gig_ethernet_pcs_pma_0_synth_1/gig_ethernet_pcs_pma_0.dcp]
add_files -quiet /scratch/skarandikar/test_ps_sfp/project_1.runs/ila_0_synth_1/ila_0.dcp
set_property used_in_implementation false [get_files /scratch/skarandikar/test_ps_sfp/project_1.runs/ila_0_synth_1/ila_0.dcp]

add_files /scratch/skarandikar/test_ps_sfp/project_1.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /scratch/skarandikar/test_ps_sfp/project_1.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /scratch/skarandikar/test_ps_sfp/project_1.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files /scratch/skarandikar/test_ps_sfp/project_1.srcs/sources_1/bd/design_1/design_1.bd]

read_verilog -library xil_defaultlib /scratch/skarandikar/test_ps_sfp/project_1.srcs/sources_1/imports/hdl/design_1_wrapper.v
read_xdc /scratch/skarandikar/test_ps_sfp/project_1.srcs/constrs_1/new/base.xdc
set_property used_in_implementation false [get_files /scratch/skarandikar/test_ps_sfp/project_1.srcs/constrs_1/new/base.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
read_xdc dont_buffer.xdc
set_property used_in_implementation false [get_files dont_buffer.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /scratch/skarandikar/test_ps_sfp/project_1.cache/wt [current_project]
set_property parent.project_dir /scratch/skarandikar/test_ps_sfp [current_project]
catch { write_hwdef -file design_1_wrapper.hwdef }
synth_design -top design_1_wrapper -part xc7z045ffg900-2
write_checkpoint design_1_wrapper.dcp
report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb
