# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

set_property BUFFER_TYPE NONE -quiet [get_ports -quiet -of [get_cells -hier -filter {REF_NAME==gig_ethernet_pcs_pma_0 || ORIG_REF_NAME==gig_ethernet_pcs_pma_0}]]
set_property BUFFER_TYPE NONE -quiet [get_ports -quiet -of [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0}]]
